### ISSUE TITLE
proper way to run

### ISSUE THREAD

**Issue by willt** [sonar-perl/sonar-perl#108]
Are these the correct steps to getting data into sonarqube? Do all these steps need to be run any time a change is made? Also if cover is running prove shouldn't cover be ran first so prove is only ran once? Do most people run this from a Makefile ?

```
# prove -t -a testReport.tgz
# cover -test -report SonarGeneric
# perlcritic --cruel --quiet --verbose "%f~|~%s~|~%l~|~%c~|~%m~|~%e~|~%p~||~%n" lib t > perlcritic_report.txt
# sonar-scanner
```

**Comment by giterlizzi** [comment]
I use a similar script in my Perl projects:

```
#!/bin/bash

(

  find -name "*.pm" -exec perltidy -b '{}' +
  find -name "*.pl" -exec perltidy -b '{}' +
  find -name "*.t" -exec perltidy -b '{}' +
  find bin/* -exec perltidy -b '{}' +
  find -name "*.bak" -exec rm -f '{}' +

  export PERL5LIB=$(pwd)/lib

  prove -t -a testReport.tgz
  cover -prefer_lib -test -report SonarGeneric

  perlcritic --cruel --quiet --verbose "%f~|~%s~|~%l~|~%c~|~%m~|~%e~|~%p~||~%n" bin lib t examples > perlcritic_report.txt

  MODULE_VERSION=$(perl -MMy::Module::Name -e 'print $My::Module::Name::VERSION;')

  sonar-scanner -Dsonar.projectVersion=$MODULE_VERSION

)
```

**Comment by willt** [comment]
I'm assuming you have a Makefile when running this?
Since cover is running make test, and test is probably calling prove you are essentially testing twice.
Couldn't you just run omit that first prove step and add -a testReport.tgz to your make test portion ?
Or if no Makefile run something like cover -prefer_lib -test -make 'prove t -a testReport' -report SonarGeneric ?

**Comment by otrosien** [comment]
This line works for me (I haven't used it anywhere though, YMMV): `cover -test -prefer_lib -make 'prove -Ilib -r t -a testReport.tar.gz;' -report SonarGeneric` (mind the semicolon, because cover will be adding parameters thinking it calls 'make')

But I've been running the test suite twice, yes. But if you're anyway running through make, you should actually be able to use the `-make` property to call back into your makefile for running the tests, no?
