### ISSUE TITLE
Re-Release 0.5.3

### ISSUE THREAD

**Issue by otrosien** [sonar-perl/sonar-perl#120]
Current release is broken because of sunsetting of bintray.

https://travis-ci.com/github/sonar-perl/sonar-perl

> ADD --chown=sonarqube:sonarqube https://bintray.com/sfeir-open-source/maven/download_file?file_path=org%2Fsfeir%2Fsonar-clover-plugin%2F4.1%2Fsonar-clover-plugin-4.1.jar /opt/sonarqube/extensions/plugins/sonar-clover-plugin-4.1.jar

We need to wait for the sonar-clover to be release on maven central.  https://github.com/sfeir-open-source/sonar-clover/issues/47

**Comment by otrosien** [comment]
@amottier FYI 

https://github.com/sonar-perl/sonar-perl/issues/120

**Comment by amottier** [comment]
@otrosien thanks for the notification. I took a look at sfeir-open-source/sonar-clover#47 and also at https://issues.sonatype.org/browse/OSSRH-67181 and in order to avoid waiting for synchronization between OSSRH and Maven Central I created #121. But only snapshot version are currently published on OSSRH so it might makes more sense to wait for an official release that should successfully be published to Maven Central.

**Comment by otrosien** [comment]
https://mvnrepository.com/artifact/io.github.sfeir-open-source/sonar-clover-plugin/4.1

**Comment by amottier** [comment]
@otrosien sorry I forgot to mention it here and only do it on #121 that sonar-clover-plugin is [available from Maven Central](https://search.maven.org/artifact/io.github.sfeir-open-source/sonar-clover-plugin/4.1/sonar-plugin) (direct download URL: https://search.maven.org/remotecontent?filepath=io/github/sfeir-open-source/sonar-clover-plugin/4.1/sonar-clover-plugin-4.1.jar).

#121 is up to date with the appropriate link.

**Comment by otrosien** [comment]
Done.
