### ISSUE TITLE
Publish sonar-perl to the Marketplace

### ISSUE THREAD

**Issue by otrosien** [sonar-perl/sonar-perl#133]
https://community.sonarsource.com/t/deploying-to-the-marketplace/35236

**Comment by ct24p** [comment]
Hello otrosien:
trying to run your sample-project on windows (strawbberry perl + TAP::Harness::Archive,Devel::Cover, Devel::Cover::Report::SonarGeneric installed), always failed at 2nd command as admin (cover -test -report SonarGeneric or your suggested command: cover -test -prefer_lib -make 'prove -Ilib -r t -a testReport.tar.gz;' -report SonarGeneric) with error below: Can't stat C:\sonar-perl\perl\sample-project\cover_db at C:/Strawberry/perl/site/lib/Devel/Cover/DB.pm line 146. Error sysopen on 'cover_db/sonar_generic.xml20844777058945': No such file or directory at C:/Strawberry/perl/site/lib/Devel/Cover/Report/SonarGeneric.pm line 47. Could you please help? thanks

**Comment by otrosien** [comment]
hey. I haven't touched this project for quite a while, but the issue you're reporting does not sound like it's related to sonarperl, rather the reporting  of coverage data. The numeric suffix after xml is fishy IMO. I would suggest something like opening a shell into the docker container and running these commands manually.

**Comment by ct24p** [comment]
Hi otrosien:
thanks for your response. This issue was coverage xml not generated for sample project (but created for Dancer). 1) Tried run on docker on linux, the scanner and sonarqube server could not communicate to each other (host.docker.internal:9000 ok for WSL but seems not for linux); 2) Could you please let us know the commands to create cover_db/sonar_generic.xml for your sample-project? (tried perl Makefile.PL/make/make testcover, no luck). thanks
