### ISSUE TITLE
PerlCodeColorizer uses a discontinued API

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [sonar-perl/sonar-perl#20]
Hello,

when compiling latest caode i got a warning whrn compiling the plugin

Note: /home/bmortier/tmp/sonar-perl/sonar-perl-plugin/src/main/java/com/github/otrosien/sonar/perl/colorizer/PerlCodeColorizer.java uses or overrides a deprecated API.

Cheers

**Comment by otrosien** [comment]
Yep, PerlCodeColorizer is the only class using a deprecated API, I haven't been able to find an equivalent replacement yet.

**Comment by otrosien** [comment]
references: https://github.com/SonarSource/sonar-xml/blob/master/sonar-xml-plugin/src/main/java/org/sonar/plugins/xml/XmlSensor.java#L111
https://groups.google.com/forum/#!searchin/sonarqube/newHighlighting%7Csort:date/sonarqube/S9H7L5uYdZU/A_on3EJ5AgAJ

seems possible without lexer/parser, but more work than right now.

**Comment by otrosien** [comment]
https://jira.sonarsource.com/browse/SONAR-7860

**Comment by vpereira** [comment]
hm as I can read in the linked jira issue, which is closed:

"Findbugs, Erlang and Puppet still rely on CodeColorizerFormat.
We should declare those plugins not compatible with 6.4 "

does it apply to perl too? As I understand it, It won't be fixed, instead version 6.4 won't support it? :(

**Comment by otrosien** [comment]
@vpereira correct. SonarQube dropped support for this API, which is fair enough, because they have been deprecating it for a long time already. So, as we stand sonar-perl does not support 6.4 for that reason. I have an issue for SonarQube 6.4 support (https://github.com/sonar-perl/sonar-perl/issues/55) but for that I need to dig deeper into the changes required.

**Comment by otrosien** [comment]
I'm keeping this ticket open for tracking a re-implementation for 6.4+
